### ISSUE TITLE
workshop function

### ISSUE THREAD

**Issue by mikulabc** [machinekoder/speed-friending-and-dating-matcher#8]
Deep relationships can only be built with consistency, this process below should achieve that:

### Day one
1. every person gets a number, writes down numbers of other people they like as usual and at the end we collect the envelopes with numbers and details

2. same evening the groups are being defined by Marked numbers, to see who marked who to build teams of interested people in each other, this will avoid having weird people, unfitting people and other reasons that people mark and did not mark people, meaning, if 

- Person A marked Person B, D & E
- Person B marked Person A & C
- Person C marked Person A, D & B
- Person D marked Person A only
- Person E marked Person A, B, C & D

The example group that will be built is: **Team 1: Person A,B,E**
(Removed are C and D Because Person D only marked Person A and not Person B & E and because Person A did not mark Person C, Person C will also NOT be included in the group, this leaves only Person A,B & E in the Group)

3. At the end of Day 1 the Teams are notified and can come to Activities of Day 2 and 3.

### Day two and three
Activities will take place with Participants A, B & E & More activities to build a strong bond in the group.

NOTE: Activities refers to any process that helps build friendships

## CODE: What is needed
An algorithm to calculate:

- Output is a list of closest groups of People from Small to Big, example output:

- Team 1: Person A,B,E,H,J,Y,Z
- Team 2: Person C,G,L,X
- Team 3: Person F,M

Important to note is that the groups really have to be strong interest groups, best example:

- Person A marked B,C
- Person B marked A,C
- Person C marked A,B

This creates the **Team with Person A,B,C - a perfect team of people.**

**Comment by machinekoder** [comment]
@schwarzeszeux Do you have an idea for an algorithm?

**Comment by schwarzeszeux** [comment]
Actually, I do. I just don't know which is a good fit for the data.
But I'm  ot sure if it's producing the desired output in a single pass. The way I understood the requirement, to be on a team, you have to mark every other team member.

@mikulabc could you share the numbers from past evnts so we have some real data to play with?

**Comment by mikulabc** [comment]
@schwarzeszeux  @machinekoder  uploaded into "example" folder

**Comment by mikulabc** [comment]
@schwarzeszeux  @machinekoder  hey guys i am actually at the stage of planning this in a direction of productive monthly cliques/groups/teams, is there any way one of you could modify the code so it outputs a 2nd CSV version with people in teams, such as discussed:

Person A marked B,C
Person B marked A,C
Person C marked A,B

Team formed is of Person A,B and C (can be a whatsapp group for starters) and they can organize their own sports, hangouts or trips..

**Comment by mikulabc** [comment]
Team 1 consists of A,B,C,D
Team 2 consists of A,B,D,E,F
etc.

**Comment by mikulabc** [comment]
relevant maybe? https://github.com/qpwo/python-simple-cycles

**Comment by zettix** [comment]
Hi Guys, at first I was BFS, then I was DFS since you need to have local information.
Depth First Search is what y'all want.  Real short:

def getClique(person, clique, seen_already):
* unseen_list = person.everyone_i_marked()
* while len(unseen_list) > 0:
* * candidate = unseen_list.pop()
* * if candidate in clique:  # already seen
* * * continue
* * seen_already.append(candidate)
* * if candidate.i_marked(person):  # they like each other.
* * * clique.append(candidate)
* * * getClique(candidate, clique, seen_already)

clique will be left with your maximum team size starting with person, with people as  items.

To make this fast, make clique, and already_seen as Sets or dicts, not lists (dictionaries with an unused value, the keys are people so search is O(1) instead of O(n) for, in this case, hashes versus lists.
For small n this is fine.

I assume the person object has the following methods:
everyone_i_marked() -> [list of people]
i_marked(other): -> true if person had marked other

**Comment by machinekoder** [comment]
Actually, for very simple cliques where everyone needs to like each other, this is a lot easier. Iterate over marked people, look if they also like everyone you liked so far, add them to the liked people and continue.

Or do I have a thinking error here?

**Comment by machinekoder** [comment]
Thinking about it a little bit more: @zettix You are right. We need to do DFS for each starting node, meaning each person. However, to make our life easier we run `SimpleMatchmaker` first so we don't need to calculate the edges every time.

**Comment by zettix** [comment]
@machinekoder one option for quick processing is to convert your directed graph into an undirected graph by eliminating all edges with no backlinks.  They you're basically done, any edge is now 2-way and you can use simple spanning tree algos to generate clique after clique. Ala
undir_edges = Set()
dir_edges = Set(all the links input)
for d in dir_edges:
- if (reverse from/to in d) is in dir_edges:
- - undir_edges.add(d)

Another way to think about it is just to filter out edges with no reverse edge to make a new, friendly graph.  The above undir_edges will have a->b and b->a iff both exist, but not a->b if b->a does not exist.
